---

- hosts: all
  become: true
  tasks:
    - name: Install Apache2 for Ubuntu VMs
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Copy index.html file to the VMs
      copy:  
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'  

